name: ollie-optimization-paper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - sympy
  - pycollo
  - numpy
  - matplotlib
  - scipy
  - casadi
  - numba
  - ca-certificates
  - openssl
