name: test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ollie-optimization-paper
          environment-file: environment.yml
          python-version: 3.10
          channels: conda-forge
      - run: |
          conda info
          conda list
